require:
  # Standard's config uses custom cops,
  # so it must be loaded along with custom Standard gems
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails


Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# Global options, like Ruby version
AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,setup}'